apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconf
data:
  nginx.conf: |
    server {
      listen       443 ssl;
      server_name  k8s_sample_frontend;
      location /api/v1 {
          proxy_pass https://server:8443;
      }
      location / {
          root   /usr/share/nginx/html;
          try_files $uri $uri/ /index.html;
      }

      ssl_certificate     /opt/ssl/localhost.crt;
      ssl_certificate_key /opt/ssl/localhost.key;

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }