services:
  server:
    image: k8s_sample_backend:latest
    environment:
      - REPOSITORY=inmemory
      - HOST_ADDRESS=0.0.0.0:8443
    ports:
      - "8443:8443"

  web:
    image: k8s_sample_frontend:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"