apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        environment: development
        role: frontend
    spec:
      volumes:
      - name: nginx
        configMap:
          name: nginxconf
      containers:
      - name: server
        image: peternagy652/k8s_sample_frontend:1.0.3
        volumeMounts:
          - name: nginx
            mountPath: "/etc/nginx/conf.d/default.conf"
            subPath: nginx.conf