apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-deployment
  labels:
    app: postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
        environment: development
        role: database
    spec:
      containers:
      - name: postgre
        image: postgres:15.4
        env:
        - name: POSTGRES_USER
          value: "k8s"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "k8s"